site_name: closest-points
site_description: The application exposes APIs that accepts a string of comma separated points and computes the closest points. It then stores them in a table.
repo_url: https://github.com/josemash4@gmail.com/closest-points
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/josemash4@gmail.com">josemash4@gmail.com</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
